language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

# Contrib is a single repository, which sub projects, change to the sub project and go-test
script:
  - cd rpsl-parser/
  - go test ./...
  - go vet ./...
